### ISSUE TITLE
Implement testing + CI.

### ISSUE THREAD

**Issue by Lyrenhex** [Lyrenhex/ENG1-Project-Part2#9]
As per the assessment brief, we require unit tests and and continuous integration (CI) infrastructure. The CI infrastructure follows from the unit tests (ideally requiring little extra work), so these are functionally the same issue.

- [x] Implement unit test system
- [x] Create unit tests for all appropriate functions of the existing implementation (+ any new functions).
- [x] Set up CI (GitHub Actions).

**Comment by Lyrenhex** [comment]
CI: build jar (can then be downloaded manually)
